apiVersion: v1
kind: Namespace
metadata:
    name: authentik
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1655antr9guh6h0jrq7wf4yrfxk0r9rkqwfxqvu9mqyrt0cxqacksc8kfz0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOVNOblY0dElvV3FlcUx5
            bzQ1aUs0L3FQYkQ2eTJYeW92SkpKbVcvV0JFCkVQV1N6Y2l0d0F5d1ZhZnVrMUFL
            eFBjSlMzZ3lQOTVxL3Yyc01YNnIyeDAKLS0tIHFCS0xFNFUzNEluR1dDY05jcUtQ
            dE5vRkdQQWR5TVo2dTl0SDc2QnA3U0UKiMMk7VAk3BodMo0MFnTl3wxl71VMSlaq
            cGlHJFVG3K8wpVm12E47mI2eQpat2zk6m1ckRS0Y6diLN/3RtZqMZw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12qyc73ua4t9qf840umss3nzpnktl9fyk4y9qfhj5cqnrwnw0yqxqtd6jzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwT3RmYkJCeTByNjRPN0JV
            RHVOMks4VThrS2dKQ2tueVM0WXJ0d05lRGdvCkNvVkZiblJkdWpmZHZRUVZHQmdT
            THpqT2JjbHB3VlNlUkpoaGlJWjZ6bjAKLS0tIFIrMy9FbS9VVnpPcHdOaTZURXRp
            R1B5aE9nMU5JYkdRWXk5MEVKSG14ckUK6XsxRfZNRbYfMR/SfS6t4aQ1WM9UswK/
            k4TSuTIrufBd8WovtzOZor1n4IvtbfvvZKKzIzYPP2S8Z3GboVy5LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-23T14:35:15Z"
    mac: ENC[AES256_GCM,data:jboRbHoMY0Qjv7EhSWGRbZ1ZVZYiTfZbASTGux+3Hx6iBlxxTVLIIx6Fsat2GMSTQvYP7m15uATPm9Bzn+FN6v2uP6K9so7KvFAuavNGbUTmGGgsyxfkT/oBj2H654W6D8AEYJn/cKIaQSw/9FFMskm1PR44Tr/2c027Dfeebfg=,iv:ELsxxhCkzmMRxCXVhrvqQFfL7tDcHat1onPz+uBt4dE=,tag:/8SKlGYgzI8Etmh+YJcU0g==,type:str]
    pgp: []
    encrypted_regex: ^(password|secret_key)$
    version: 3.9.1
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: authentik
    namespace: authentik
spec:
    interval: 24h
    url: https://charts.goauthentik.io
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1655antr9guh6h0jrq7wf4yrfxk0r9rkqwfxqvu9mqyrt0cxqacksc8kfz0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOVNOblY0dElvV3FlcUx5
            bzQ1aUs0L3FQYkQ2eTJYeW92SkpKbVcvV0JFCkVQV1N6Y2l0d0F5d1ZhZnVrMUFL
            eFBjSlMzZ3lQOTVxL3Yyc01YNnIyeDAKLS0tIHFCS0xFNFUzNEluR1dDY05jcUtQ
            dE5vRkdQQWR5TVo2dTl0SDc2QnA3U0UKiMMk7VAk3BodMo0MFnTl3wxl71VMSlaq
            cGlHJFVG3K8wpVm12E47mI2eQpat2zk6m1ckRS0Y6diLN/3RtZqMZw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12qyc73ua4t9qf840umss3nzpnktl9fyk4y9qfhj5cqnrwnw0yqxqtd6jzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwT3RmYkJCeTByNjRPN0JV
            RHVOMks4VThrS2dKQ2tueVM0WXJ0d05lRGdvCkNvVkZiblJkdWpmZHZRUVZHQmdT
            THpqT2JjbHB3VlNlUkpoaGlJWjZ6bjAKLS0tIFIrMy9FbS9VVnpPcHdOaTZURXRp
            R1B5aE9nMU5JYkdRWXk5MEVKSG14ckUK6XsxRfZNRbYfMR/SfS6t4aQ1WM9UswK/
            k4TSuTIrufBd8WovtzOZor1n4IvtbfvvZKKzIzYPP2S8Z3GboVy5LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-23T14:35:15Z"
    mac: ENC[AES256_GCM,data:jboRbHoMY0Qjv7EhSWGRbZ1ZVZYiTfZbASTGux+3Hx6iBlxxTVLIIx6Fsat2GMSTQvYP7m15uATPm9Bzn+FN6v2uP6K9so7KvFAuavNGbUTmGGgsyxfkT/oBj2H654W6D8AEYJn/cKIaQSw/9FFMskm1PR44Tr/2c027Dfeebfg=,iv:ELsxxhCkzmMRxCXVhrvqQFfL7tDcHat1onPz+uBt4dE=,tag:/8SKlGYgzI8Etmh+YJcU0g==,type:str]
    pgp: []
    encrypted_regex: ^(password|secret_key)$
    version: 3.9.1
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: authentik
    namespace: authentik
spec:
    interval: 30m
    chart:
        spec:
            chart: authentik
            version: '*'
            sourceRef:
                kind: HelmRepository
                name: authentik
                namespace: authentik
            interval: 12h
    values:
        authentik:
            secret_key: ENC[AES256_GCM,data:xhaDJIZHnTeAaFI0CBfIXOo0/C+35UU3q6DuzUMfYmYXYP0xB96YZKtK6Hsb/mr0JIjtU7aMT2OgKUUV4MONnh4NgoWp6t/g/cGNwYu3/UM=,iv:TwXs9dDOvdJKren8Rq1Z2FPLNkUAX5Q1aKjThYbO73U=,tag:fTWrpQbsym/szoC/xrHUwQ==,type:str]
            error_reporting:
                enabled: false
            postgresql:
                password: ENC[AES256_GCM,data:3mshAeaMT3FU0GqZkCYyBuE/RVjnpb47w8zrZT+gtub+yhcmI5dug0w0Z3geY3GjZR17h3bR0EJLnEyFnImMUvGOASsZgUFKWZrbSm2QFZs=,iv:Nstdgt3WFSWRf3gGQoU5rBlF5DyP9rNQwGCdUeTmrg4=,tag:GOTV68Vlb0gMO7TSboxp8w==,type:str]
        server:
            ingress:
                ingressClassName: nginx
                annotations:
                    cert-manager.io/cluster-issuer: letsencrypt
                enabled: true
                hosts:
                    - auth.phorge.fr
                tls:
                    - secretName: authentik-tls
                      hosts:
                        - auth.phorge.fr
        postgresql:
            enabled: true
            auth:
                password: ENC[AES256_GCM,data:yxC0U5wyP3VYQtn4+i/sRGFFa4bNuCNTmus6bcL77Do9wZbpzNd71v4P1sFDuXMtIzSIvBaQKm1f4362VBfV0kW8RETDoNPkmYRGO2zCjKU=,iv:MiLY9tMXrVLzqWr/AHqfA2ac/g3BEsvJn/C4PoC2RS8=,tag:xzu6vtPg1y9kh1Y4idcMsA==,type:str]
        redis:
            enabled: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1655antr9guh6h0jrq7wf4yrfxk0r9rkqwfxqvu9mqyrt0cxqacksc8kfz0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOVNOblY0dElvV3FlcUx5
            bzQ1aUs0L3FQYkQ2eTJYeW92SkpKbVcvV0JFCkVQV1N6Y2l0d0F5d1ZhZnVrMUFL
            eFBjSlMzZ3lQOTVxL3Yyc01YNnIyeDAKLS0tIHFCS0xFNFUzNEluR1dDY05jcUtQ
            dE5vRkdQQWR5TVo2dTl0SDc2QnA3U0UKiMMk7VAk3BodMo0MFnTl3wxl71VMSlaq
            cGlHJFVG3K8wpVm12E47mI2eQpat2zk6m1ckRS0Y6diLN/3RtZqMZw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12qyc73ua4t9qf840umss3nzpnktl9fyk4y9qfhj5cqnrwnw0yqxqtd6jzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwT3RmYkJCeTByNjRPN0JV
            RHVOMks4VThrS2dKQ2tueVM0WXJ0d05lRGdvCkNvVkZiblJkdWpmZHZRUVZHQmdT
            THpqT2JjbHB3VlNlUkpoaGlJWjZ6bjAKLS0tIFIrMy9FbS9VVnpPcHdOaTZURXRp
            R1B5aE9nMU5JYkdRWXk5MEVKSG14ckUK6XsxRfZNRbYfMR/SfS6t4aQ1WM9UswK/
            k4TSuTIrufBd8WovtzOZor1n4IvtbfvvZKKzIzYPP2S8Z3GboVy5LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-23T14:35:15Z"
    mac: ENC[AES256_GCM,data:jboRbHoMY0Qjv7EhSWGRbZ1ZVZYiTfZbASTGux+3Hx6iBlxxTVLIIx6Fsat2GMSTQvYP7m15uATPm9Bzn+FN6v2uP6K9so7KvFAuavNGbUTmGGgsyxfkT/oBj2H654W6D8AEYJn/cKIaQSw/9FFMskm1PR44Tr/2c027Dfeebfg=,iv:ELsxxhCkzmMRxCXVhrvqQFfL7tDcHat1onPz+uBt4dE=,tag:/8SKlGYgzI8Etmh+YJcU0g==,type:str]
    pgp: []
    encrypted_regex: ^(password|secret_key)$
    version: 3.9.1
