apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
 name: default-bgp-peering-policy
spec:
 nodeSelector:
   matchLabels:
     bgp-policy: default
 virtualRouters:
 - localASN: 64512
   exportPodCIDR: false
   neighbors:
    - peerAddress: '10.1.0.254/32'
      peerASN: 64512
   serviceSelector:
     matchExpressions:
       - {key: somekey, operator: NotIn, values: ['never-used-value']}